FROM node:22-alpine

RUN apk add --no-cache libc6-compat curl

WORKDIR /app

# Copy package files and install dependencies
COPY package.json package-lock.json ./
RUN npm i && npm cache clean --force

ENV NODE_ENV=development
ENV CHOKIDAR_USEPOLLING=true
ENV WATCHPACK_POLLING=true

EXPOSE 3000

CMD [ "npm", "run", "dev:socket" ]